name: Build & Release (MCP)

on:
  push:
    branches: [main]

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Ensure artifact exists
        run: test -f cloudglue-mcp-server.mcpb

      - name: Generate version string
        id: ver
        run: echo "version=0.0.$(date -u +'%Y%m%dT%H%M%SZ')" >> "$GITHUB_OUTPUT"

      - name: SHA256 checksum
        run: |
          sha256sum cloudglue-mcp-server.mcpb > SHA256SUMS.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.ver.outputs.version }}
          name: ${{ steps.ver.outputs.version }}
          generate_release_notes: true
          files: |
            cloudglue-mcp-server.mcpb
            SHA256SUMS.txt
          body: |
            Commit: ${{ github.sha }}
            Ref: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
